### ISSUE TITLE
Error while navigating between bottom tabs 

### ISSUE THREAD

**Issue by gemy21ce** [gemy21ce/mcnd_mobile#10]
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  UncontrolledProviderScope
The widget which was currently being built when the offending call was made was:
  PrayerTimesPage
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4138:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4153:6)
#2      ProviderElement._debugMarkWillChang<…>
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Instance of 'Error'
#0      StateNotifier.state= (package:state_notifier/state_notifier.dart:173:7)
#1      PrayerTimesViewModel.fetchTimes (package:mcnd_mobile/ui/prayer_times/prayer_times_viewmodel.dart:33:5)
#2      PrayerTimesPage.build.<anonymous closure> (package:mcnd_mobile/ui/prayer_times/prayer_times_page.dart:14:29)
#3      useOnce.<anonymous closure> (package:mcnd_mobile/ui/shared/hooks/use_once.dart:4:15)
#4      _EffectHookState.scheduleEffect (package:flutter_hooks/src/primitives.dart:181:27)
#5      _EffectHookState.initHook (package:flutter_hooks/src/primitives.dart:161:5)
#6      _extension#0._createHookState (package:flutter_hooks/src/framework.dart:319:9)
#7      _extension#0._appendHook (package:flutter_hooks/src/framework.dart:330:20)
#8      HookElement._use (package:flutter_hooks/src/framework.dart:439:7)
#9      Hook.use (package:flutter_hooks/src/framework.dart:140:45)
#10     use (package:flutter_hooks/src/framework.dart<…>

**Comment by TarekkMA** [comment]
fixed in #8
